name: BierXP
main: de.bierxp.BierXP
version: 1.0
api-version: 1.21
author: RicoDessau

commands:
  bierxp:
    description: XP Banker Command
    usage: /bierxp
    permission: bierxp.admin

permissions:
  bierxp.admin:
    default: op
