name: BierXP
main: de.bierxp.BierXP
version: 1.0
api-version: 1.21
author: RicoDessau
description: XP-Bank Plugin mit NPC

commands:
  bierxp:
    description: Hauptbefehl für BierXP
    usage: /bierxp
    permission: bierxp.admin

permissions:
  bierxp.admin:
    description: Erlaubt das Verwalten des BierXP-Systems
    default: op
