name: Build BierXP Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Java 21 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Mit Maven bauen
      run: mvn -B package --file pom.xml

    - name: Artifact hochladen (Die fertige .jar)
      uses: actions/upload-artifact@v4
      with:
        name: BierXP-Plugin
        path: target/*.jar
